"""remove url and source, add unique constraint on title+updated_at

Revision ID: 0b2595626cc8
Revises: b11ed9840c92
Create Date: 2025-12-29 16:49:58.685174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b2595626cc8'
down_revision: Union[str, Sequence[str], None] = 'b11ed9840c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_url'), table_name='news')
    op.create_unique_constraint('uq_news_title_updated', 'news', ['title', 'updated_at'])
    op.drop_column('news', 'url')
    op.drop_column('news', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('source', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('news', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_news_title_updated', 'news', type_='unique')
    op.create_index(op.f('ix_news_url'), 'news', ['url'], unique=True)
    # ### end Alembic commands ###
