"""init tables

Revision ID: 8c11887adc8c
Revises: 
Create Date: 2025-09-23 10:05:00.942450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c11887adc8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coins_id'), table_name='coins')
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.drop_table('coins')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_index(op.f('ix_news_url'), table_name='news')
    op.drop_table('news')
    op.drop_table('news_coins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_coins',
    sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], name=op.f('news_coins_coin_id_fkey')),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('news_coins_news_id_fkey')),
    sa.PrimaryKeyConstraint('news_id', 'coin_id', name=op.f('news_coins_pkey'))
    )
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sentiment_norm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('news_pkey'))
    )
    op.create_index(op.f('ix_news_url'), 'news', ['url'], unique=True)
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('coins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('coins_pkey'))
    )
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=True)
    op.create_index(op.f('ix_coins_id'), 'coins', ['id'], unique=False)
    # ### end Alembic commands ###
