"""Add indexes and fix unique constraints

Revision ID: fe1c229f1a54
Revises: 0b2595626cc8
Create Date: 2026-01-05 00:35:59.384291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1c229f1a54'
down_revision: Union[str, Sequence[str], None] = '0b2595626cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_news_title_updated'), 'news', type_='unique')
    op.create_index('idx_news_published_at', 'news', ['published_at'], unique=False)
    op.create_index('idx_news_sentiment', 'news', ['sentiment_label'], unique=False)
    op.create_unique_constraint('uq_news_title_published', 'news', ['title', 'published_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_news_title_published', 'news', type_='unique')
    op.drop_index('idx_news_sentiment', table_name='news')
    op.drop_index('idx_news_published_at', table_name='news')
    op.create_unique_constraint(op.f('uq_news_title_updated'), 'news', ['title', 'updated_at'])
    # ### end Alembic commands ###
